DROP DATABASE if exists`eagle_museum`;
CREATE SCHEMA `eagle_museum` DEFAULT CHARACTER SET utf8mb4 ;
CREATE TABLE `eagle_museum`.`exhibition` (
  `EXHIBITION_ID` int NOT NULL AUTO_INCREMENT,
  `EXHIBITION_TYPE` int NOT NULL,
  `EXHIBITION_NAME` varchar(255) NOT NULL,
  `EXHIBITION_START_DATE` date NOT NULL,
  `EXHIBITION_END_DATE` date NOT NULL,
  `EXHIBITION_ARTICLE` varchar(999) NOT NULL,
  `EXHIBITION_STATUS` int NOT NULL,
  `LAST_UPDATE_TIME` date NOT NULL,
  `LOCATION_ID` int NOT NULL,
  `EXHIBITION_IMG` longblob,
  PRIMARY KEY (`EXHIBITION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='展覽資料表';